export const phonePrefixes = [
  { country: "Argelia", code: "+213", flag: "🇩🇿" },
  { country: "Argentina", code: "+54", flag: "🇦🇷" },
  { country: "Australia", code: "+61", flag: "🇦🇺" },
  { country: "Austria", code: "+43", flag: "🇦🇹" },
  { country: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { country: "Bélgica", code: "+32", flag: "🇧🇪" },
  { country: "Bolivia", code: "+591", flag: "🇧🇴" },
  { country: "Brasil", code: "+55", flag: "🇧🇷" },
  { country: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { country: "Canadá", code: "+1", flag: "🇨🇦" },
  { country: "Chile", code: "+56", flag: "🇨🇱" },
  { country: "Colombia", code: "+57", flag: "🇨🇴" },
  { country: "Chipre", code: "+357", flag: "🇨🇾" },
  { country: "República Checa", code: "+420", flag: "🇨🇿" },
  { country: "República Democrática del Congo", code: "+243", flag: "🇨🇩" },
  { country: "Dinamarca", code: "+45", flag: "🇩🇰" },
  { country: "República Dominicana", code: "+1-809", flag: "🇩🇴" },
  { country: "Ecuador", code: "+593", flag: "🇪🇨" },
  { country: "Egipto", code: "+20", flag: "🇪🇬" },
  { country: "El Salvador", code: "+503", flag: "🇸🇻" },
  { country: "Francia", code: "+33", flag: "🇫🇷" },
  { country: "Georgia", code: "+995", flag: "🇬🇪" },
  { country: "Alemania", code: "+49", flag: "🇩🇪" },
  { country: "Ghana", code: "+233", flag: "🇬🇭" },
  { country: "Grecia", code: "+30", flag: "🇬🇷" },
  { country: "Guatemala", code: "+502", flag: "🇬🇹" },
  { country: "Honduras", code: "+504", flag: "🇭🇳" },
  { country: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { country: "Hungría", code: "+36", flag: "🇭🇺" },
  { country: "India", code: "+91", flag: "🇮🇳" },
  { country: "Indonesia", code: "+62", flag: "🇮🇩" },
  { country: "Irak", code: "+964", flag: "🇮🇶" },
  { country: "Irlanda", code: "+353", flag: "🇮🇪" },
  { country: "Israel", code: "+972", flag: "🇮🇱" },
  { country: "Italia", code: "+39", flag: "🇮🇹" },
  { country: "Japón", code: "+81", flag: "🇯🇵" },
  { country: "Jordania", code: "+962", flag: "🇯🇴" },
  { country: "Kenia", code: "+254", flag: "🇰🇪" },
  { country: "Malasia", code: "+60", flag: "🇲🇾" },
  { country: "México", code: "+52", flag: "🇲🇽" },
  { country: "Marruecos", code: "+212", flag: "🇲🇦" },
  { country: "Nepal", code: "+977", flag: "🇳🇵" },
  { country: "Nueva Zelanda", code: "+64", flag: "🇳🇿" },
  { country: "Nigeria", code: "+234", flag: "🇳🇬" },
  { country: "Noruega", code: "+47", flag: "🇳🇴" },
  { country: "Perú", code: "+51", flag: "🇵🇪" },
  { country: "Polonia", code: "+48", flag: "🇵🇱" },
  { country: "Portugal", code: "+351", flag: "🇵🇹" },
  { country: "Puerto Rico", code: "+1-787", flag: "🇵🇷" },
  { country: "Rumania", code: "+40", flag: "🇷🇴" },
  { country: "Arabia Saudita", code: "+966", flag: "🇸🇦" },
  { country: "Singapur", code: "+65", flag: "🇸🇬" },
  { country: "Sudáfrica", code: "+27", flag: "🇿🇦" },
  { country: "Corea del Sur", code: "+82", flag: "🇰🇷" },
  { country: "España", code: "+34", flag: "🇪🇸" },
  { country: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { country: "Suecia", code: "+46", flag: "🇸🇪" },
  { country: "Suiza", code: "+41", flag: "🇨🇭" },
  { country: "Taiwán", code: "+886", flag: "🇹🇼" },
  { country: "Tanzania", code: "+255", flag: "🇹🇿" },
  { country: "Tailandia", code: "+66", flag: "🇹🇭" },
  { country: "Países Bajos", code: "+31", flag: "🇳🇱" },
  { country: "Filipinas", code: "+63", flag: "🇵🇭" },
  { country: "Túnez", code: "+216", flag: "🇹🇳" },
  { country: "Turquía", code: "+90", flag: "🇹🇷" },
  { country: "Uganda", code: "+256", flag: "🇺🇬" },
  { country: "Ucrania", code: "+380", flag: "🇺🇦" },
  { country: "Emiratos Árabes Unidos", code: "+971", flag: "🇦🇪" },
  { country: "Reino Unido", code: "+44", flag: "🇬🇧" },
  { country: "Estados Unidos", code: "+1", flag: "🇺🇸" },
].sort((a, b) => a.country.localeCompare(b.country, "es"));
